apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbonara
  labels:
    app: food
    type: carbonara
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food
      type: carbonara
  template:
    metadata:
      labels:
        app: food
        type: carbonara
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: carbonara
        image: "<region>-docker.pkg.dev/<projectname>/<reponame>/carbonara:latest"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 80
