apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza
  labels:
    app: food
    type: pizza
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food
      type: pizza
  template:
    metadata:
      labels:
        app: food
        type: pizza
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: pizza
        image: "<region>-docker.pkg.dev/<projectname>/<reponame>/pizza:latest"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 80
